version: '3.4'

networks:
  stackoverflowlight-api-dev:
    driver: bridge 

services:
  stackoverflowlight-api:
    image: stackoverflowlight-api:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: StackOverflowLight-api/Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=stackoverflowdb;username=stackoverflow;password=stackoverflow"
    networks:
      - stackoverflowlight-api-dev 
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "stackoverflow"
      POSTGRES_PASSWORD: "stackoverflow"
      POSTGRES_DB: "stackoverflowdb"
    networks:
      - stackoverflowlight-api-dev
volumes:
  db_volume:
         
    
     